NUM = int(input('TABUADA DO: '))
print('-----------------')
print ('{} x {} = {}' .format(NUM , 1, NUM*1))
print ('{} x {} = {}' .format(NUM , 2, NUM*2))
print ('{} x {} = {}' .format(NUM , 3, NUM*3))
print ('{} x {} = {}' .format(NUM , 4, NUM*4))
print ('{} x {} = {}' .format(NUM , 5, NUM*5))
print ('{} x {} = {}' .format(NUM , 6, NUM*6))
print ('{} x {} = {}' .format(NUM , 7, NUM*7))
print ('{} x {} = {}' .format(NUM , 8, NUM*8))
print ('{} x {} = {}' .format(NUM , 9, NUM*9))
print ('{} x {} = {}' .format(NUM , 10, NUM*10))